name = "bluemeridian"
compatibility_date = "2026-06-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "bluemeridian_db"
database_id = "b2f59f64-1273-495e-a224-306c4f2ea357"

[[r2_buckets]]
binding = "FILES"
bucket_name = "bluemeridian"
